name: Lagrange.Kritor Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtimeIdentifier:
          [
            win-x64,
            win-x86,
            linux-x64,
            linux-arm,
            linux-arm64,
            osx-x64,
            osx-arm64,
            linux-musl-x64,
            linux-musl-arm,
            linux-musl-arm64,
          ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Lagrange.Kritor .NET 8.0
        run: dotnet publish Lagrange.Kritor/Lagrange.Kritor.csproj --no-self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net8.0

      - name: Upload binary files(${{ matrix.runtimeIdentifier }}) for .NET 8.0
        uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: Lagrange.Kritor_${{ matrix.runtimeIdentifier }}_net8.0_NoSelfContained
          path: Lagrange.Kritor/bin/Release/net8.0/${{ matrix.runtimeIdentifier }}/publish
